"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollectionNames = void 0;
var CollectionNames;
(function (CollectionNames) {
    CollectionNames["ai_prompts"] = "ai_prompts";
    CollectionNames["block_button"] = "block_button";
    CollectionNames["block_button_group"] = "block_button_group";
    CollectionNames["block_form"] = "block_form";
    CollectionNames["block_gallery"] = "block_gallery";
    CollectionNames["block_gallery_items"] = "block_gallery_items";
    CollectionNames["block_hero"] = "block_hero";
    CollectionNames["block_posts"] = "block_posts";
    CollectionNames["block_pricing"] = "block_pricing";
    CollectionNames["block_pricing_cards"] = "block_pricing_cards";
    CollectionNames["block_richtext"] = "block_richtext";
    CollectionNames["form_fields"] = "form_fields";
    CollectionNames["forms"] = "forms";
    CollectionNames["form_submissions"] = "form_submissions";
    CollectionNames["form_submission_values"] = "form_submission_values";
    CollectionNames["globals"] = "globals";
    CollectionNames["navigation"] = "navigation";
    CollectionNames["navigation_items"] = "navigation_items";
    CollectionNames["page_blocks"] = "page_blocks";
    CollectionNames["pages"] = "pages";
    CollectionNames["posts"] = "posts";
    CollectionNames["redirects"] = "redirects";
    CollectionNames["directus_access"] = "directus_access";
    CollectionNames["directus_activity"] = "directus_activity";
    CollectionNames["directus_collections"] = "directus_collections";
    CollectionNames["directus_comments"] = "directus_comments";
    CollectionNames["directus_fields"] = "directus_fields";
    CollectionNames["directus_files"] = "directus_files";
    CollectionNames["directus_folders"] = "directus_folders";
    CollectionNames["directus_migrations"] = "directus_migrations";
    CollectionNames["directus_permissions"] = "directus_permissions";
    CollectionNames["directus_policies"] = "directus_policies";
    CollectionNames["directus_presets"] = "directus_presets";
    CollectionNames["directus_relations"] = "directus_relations";
    CollectionNames["directus_revisions"] = "directus_revisions";
    CollectionNames["directus_roles"] = "directus_roles";
    CollectionNames["directus_sessions"] = "directus_sessions";
    CollectionNames["directus_settings"] = "directus_settings";
    CollectionNames["directus_users"] = "directus_users";
    CollectionNames["directus_webhooks"] = "directus_webhooks";
    CollectionNames["directus_dashboards"] = "directus_dashboards";
    CollectionNames["directus_panels"] = "directus_panels";
    CollectionNames["directus_notifications"] = "directus_notifications";
    CollectionNames["directus_shares"] = "directus_shares";
    CollectionNames["directus_flows"] = "directus_flows";
    CollectionNames["directus_operations"] = "directus_operations";
    CollectionNames["directus_translations"] = "directus_translations";
    CollectionNames["directus_versions"] = "directus_versions";
    CollectionNames["directus_extensions"] = "directus_extensions";
})(CollectionNames || (exports.CollectionNames = CollectionNames = {}));
