packages:
  - apps/**
  - packages/**
  - tools/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - sharp
  - unrs-resolver
  - vue-demi
